version: '3.3'

services:
  ui:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.ui
    image: ghcr.io/softuni-internal/judge_web_ui:dev-2022-08-01
    container_name: ui_instance
    ports:
      - "5002:80"
    restart: on-failure
    volumes:
      - ./Logs:/Logs
      - ./Keys:/Keys
    env_file:
      - Docker/common/common.env
      - Docker/common/db.env
      - Docker/applications/ui/ui.env
    extra_hosts:
      - "db:host-gateway"
      - "localhost:host-gateway"
      - "redis:host-gateway"
  administration:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.administration
    image: administration
    container_name: administration_instance
    ports:
      - "5001:80"
    restart: on-failure
    volumes:
      - ./Logs:/Logs
      - ./Keys:/Keys
    env_file:
      - Docker/common/common.env
      - Docker/common/db.env
      - Docker/applications/administration/administration.env
    extra_hosts:
      - "db:host-gateway"
      - "localhost:host-gateway"
