version: '3.3'

services:
  ui:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.ui
    image: ghcr.io/softuni-internal/judge_web_ui:dev-2022-08-01
    container_name: ui_instance
    ports:
      - "5002:80"
    restart: on-failure
    volumes:
      - ./Logs:/Logs
    env_file:
      - Docker/common/common.env
      - Docker/common/db.env
      - Docker/applications/ui/ui.env
    extra_hosts:
      - "db:host-gateway"
      - "mq:host-gateway"
      - "localhost:host-gateway"
      - "redis:host-gateway"
  administration:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.administration
    image: administration
    container_name: administration_instance
    ports:
      - "5001:80"
    restart: on-failure
    volumes:
      - ./Logs:/Logs
    env_file:
      - Docker/common/common.env
      - Docker/common/db.env
      - Docker/applications/administration/administration.env
    extra_hosts:
      - "db:host-gateway"
      - "mq:host-gateway"
      - "localhost:host-gateway"
  worker:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.worker
    image: ghcr.io/softuni-internal/judge_worker:v2-latest
    ports:
      - "8003:80"
    container_name: judge_worker_instance
    restart: on-failure
    env_file:
      - Docker/common/common.env
      - Docker/applications/worker/worker.env
    volumes:
      - ./Logs:/Logs
      - /tmp/ExecutionStrategies:/tmp/ExecutionStrategies
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "mq:host-gateway"
      - "localhost:host-gateway"
      - "host.docker.internal:host-gateway"
  mq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: mq_instance
    hostname: "judge-mq"
    environment:
      DEFAULT_USER_PASSWORD: myS3cretPass2
    volumes:
      - rabbitmq_data:/var/lib/rabbitmqvolumes:rw
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
  redis:
    image: "redis:5.0"
    ports:
      - "6379:6379"
    container_name: redis_instance
    hostname: "judge-rd"
    command: "redis-server --requirepass redisPass123"
    
volumes:
  rabbitmq_data:
