version: '3.8'

services:
  ui:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.ui
    image: judge_web_ui
    container_name: web_ui_instance
    ports:
      - "5002:80"
    restart: on-failure
    volumes:
      - ./Logs:/Logs
    env_file:
      - Docker/common/common.env
      - Docker/common/db.env
      - Docker/applications/ui/ui.env
    extra_hosts:
      - "db:host-gateway"
    links:
      - mq
      - redis
    depends_on:
      - mq
      - redis
  administration:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.administration
    image: judge_administration
    container_name: judge_administration_instance
    ports:
      - "5001:80"
    restart: on-failure
    volumes:
      - ./Logs:/Logs
    env_file:
      - Docker/common/common.env
      - Docker/common/db.env
      - Docker/applications/administration/administration.env
    extra_hosts:
      - "db:host-gateway"
    links:
      - mq
      - redis
    depends_on:
      - mq
      - redis
  worker:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.worker
    image: judge_worker
    ports:
      - "8003:80"
    container_name: judge_worker_instance
    restart: on-failure
    env_file:
      - Docker/common/common.env
      - Docker/applications/worker/worker.env
    volumes:
      - ./Logs:/Logs
      - /tmp/ExecutionStrategies:/tmp/ExecutionStrategies
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - mq
      - sql_server
      - mysql
      - postgres
    depends_on:
      - mq
      - sql_server
      - mysql
      - postgres

# External services
  mq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: mq_instance
    hostname: "judge-mq"
    environment:
      DEFAULT_USER_PASSWORD: myS3cretPass2
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
    container_name: redis_instance
    hostname: "judge-rd"
    command: "redis-server --requirepass redisPass123"
## Worker dependencies
  sql_server:
      image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
      restart: always
      environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: 1123QwER
  mysql:
    image: mysql/mysql-server:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1123QwER
      MYSQL_ROOT_HOST: '%'
  postgres:
      image: postgres:15
      restart: always
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: 1123QwER
        POSTGRES_USER: postgres
    
volumes:
  rabbitmq_data:
