// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OJS.Data;

#nullable disable

namespace OJS.Data.Migrations
{
    [DbContext(typeof(OjsDbContext))]
    [Migration("20240422111251_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OJS.Data.Models.AccessLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostParams")
                        .HasColumnType("text");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AccessLogs");
                });

            modelBuilder.Entity("OJS.Data.Models.Checkers.Checker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DllFile")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Parameter")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Checkers");
                });

            modelBuilder.Entity("OJS.Data.Models.Contests.Contest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowParallelSubmissionsInTasks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("AutoChangeTestsFeedbackVisibility")
                        .HasColumnType("boolean");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ContestPassword")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<int>("LimitBetweenSubmissions")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewIpPassword")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<short>("NumberOfProblemGroups")
                        .HasColumnType("smallint");

                    b.Property<double>("OrderBy")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("PracticeEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PracticePassword")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("PracticeStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Contests");
                });

            modelBuilder.Entity("OJS.Data.Models.Contests.ContestCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("OrderBy")
                        .HasColumnType("double precision");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ContestCategories");
                });

            modelBuilder.Entity("OJS.Data.Models.Contests.ExamGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContestId")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalAppId")
                        .HasColumnType("text");

                    b.Property<int?>("ExternalExamGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.ToTable("ExamGroups");
                });

            modelBuilder.Entity("OJS.Data.Models.FeedbackReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FeedbackReports");
                });

            modelBuilder.Entity("OJS.Data.Models.Ip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Ips");
                });

            modelBuilder.Entity("OJS.Data.Models.IpInContest", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("integer");

                    b.Property<int>("IpId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOriginallyAllowed")
                        .HasColumnType("boolean");

                    b.HasKey("ContestId", "IpId");

                    b.HasIndex("IpId");

                    b.ToTable("ContestIps");
                });

            modelBuilder.Entity("OJS.Data.Models.LecturerInContest", b =>
                {
                    b.Property<string>("LecturerId")
                        .HasColumnType("text");

                    b.Property<int>("ContestId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LecturerId", "ContestId");

                    b.HasIndex("ContestId");

                    b.ToTable("LecturersInContests");
                });

            modelBuilder.Entity("OJS.Data.Models.LecturerInContestCategory", b =>
                {
                    b.Property<string>("LecturerId")
                        .HasColumnType("text");

                    b.Property<int>("ContestCategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LecturerId", "ContestCategoryId");

                    b.HasIndex("ContestCategoryId");

                    b.ToTable("LecturersInContestCategories");
                });

            modelBuilder.Entity("OJS.Data.Models.Participants.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContestId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsInvalidated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOfficial")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ParticipationEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ParticipationStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalScoreSnapshot")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TotalScoreSnapshotModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("UserId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("OJS.Data.Models.Participants.ParticipantScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOfficial")
                        .HasColumnType("boolean");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<string>("ParticipantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("ProblemId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubmissionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("ProblemId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("ParticipantScores");
                });

            modelBuilder.Entity("OJS.Data.Models.ProblemForParticipant", b =>
                {
                    b.Property<int>("ProblemId")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.HasKey("ProblemId", "ParticipantId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("ProblemsForParticipants");
                });

            modelBuilder.Entity("OJS.Data.Models.Problems.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AdditionalFiles")
                        .HasColumnType("bytea");

                    b.Property<int?>("CheckerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<short>("MaximumPoints")
                        .HasColumnType("smallint");

                    b.Property<int>("MemoryLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("OrderBy")
                        .HasColumnType("double precision");

                    b.Property<int>("ProblemGroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowDetailedFeedback")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowResults")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("SolutionSkeleton")
                        .HasColumnType("bytea");

                    b.Property<int?>("SourceCodeSizeLimit")
                        .HasColumnType("integer");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CheckerId");

                    b.HasIndex("ProblemGroupId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("OJS.Data.Models.Problems.ProblemGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContestId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("OrderBy")
                        .HasColumnType("double precision");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.ToTable("ProblemGroups");
                });

            modelBuilder.Entity("OJS.Data.Models.Problems.ProblemResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("File")
                        .HasColumnType("bytea");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("OrderBy")
                        .HasColumnType("double precision");

                    b.Property<int>("ProblemId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.ToTable("ProblemResources");
                });

            modelBuilder.Entity("OJS.Data.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("OJS.Data.Models.Submissions.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompilerComment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedExecutionOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileExtension")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsCompiledSuccessfully")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("ProblemId")
                        .HasColumnType("integer");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProcessingComment")
                        .HasColumnType("text");

                    b.Property<byte[]>("SolutionSkeleton")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("StartedExecutionOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SubmissionTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("TestRunsCache")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("ProblemId");

                    b.HasIndex("SubmissionTypeId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("OJS.Data.Models.Submissions.SubmissionForProcessing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<bool>("Processing")
                        .HasColumnType("boolean");

                    b.Property<string>("SerializedException")
                        .HasColumnType("text");

                    b.Property<string>("SerializedExecutionDetails")
                        .HasColumnType("text");

                    b.Property<string>("SerializedExecutionResult")
                        .HasColumnType("text");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("SubmissionsForProcessing");
                });

            modelBuilder.Entity("OJS.Data.Models.Submissions.SubmissionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalCompilerArguments")
                        .HasColumnType("text");

                    b.Property<bool>("AllowBinaryFilesUpload")
                        .HasColumnType("boolean");

                    b.Property<string>("AllowedFileExtensions")
                        .HasColumnType("text");

                    b.Property<int>("CompilerType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ExecutionStrategyType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSelectedByDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("SubmissionTypes");
                });

            modelBuilder.Entity("OJS.Data.Models.SubmissionTypeInProblem", b =>
                {
                    b.Property<int>("SubmissionTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ProblemId")
                        .HasColumnType("integer");

                    b.Property<int?>("MemoryLimit")
                        .HasColumnType("integer");

                    b.Property<byte[]>("SolutionSkeleton")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int?>("TimeLimit")
                        .HasColumnType("integer");

                    b.HasKey("SubmissionTypeId", "ProblemId");

                    b.HasIndex("ProblemId");

                    b.ToTable("SubmissionTypeProblems");
                });

            modelBuilder.Entity("OJS.Data.Models.Tests.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("HideInput")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("InputData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsOpenTest")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrialTest")
                        .HasColumnType("boolean");

                    b.Property<double>("OrderBy")
                        .HasColumnType("double precision");

                    b.Property<byte[]>("OutputData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("ProblemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("OJS.Data.Models.Tests.TestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckerComment")
                        .HasColumnType("text");

                    b.Property<string>("ExecutionComment")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedOutputFragment")
                        .HasColumnType("text");

                    b.Property<long>("MemoryUsed")
                        .HasColumnType("bigint");

                    b.Property<int>("ResultType")
                        .HasColumnType("integer");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer");

                    b.Property<int>("TestId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeUsed")
                        .HasColumnType("integer");

                    b.Property<string>("UserOutputFragment")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("TestId");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("OJS.Data.Models.UserInExamGroup", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("ExamGroupId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ExamGroupId");

                    b.HasIndex("ExamGroupId");

                    b.ToTable("UsersInExamGroups");
                });

            modelBuilder.Entity("OJS.Data.Models.Users.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("OJS.Data.Models.Users.UserInRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("OJS.Data.Models.Users.UserProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("OJS.Data.Models.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OJS.Data.Models.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OJS.Data.Models.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OJS.Data.Models.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OJS.Data.Models.AccessLog", b =>
                {
                    b.HasOne("OJS.Data.Models.Users.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OJS.Data.Models.Contests.Contest", b =>
                {
                    b.HasOne("OJS.Data.Models.Contests.ContestCategory", "Category")
                        .WithMany("Contests")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OJS.Data.Models.Contests.ContestCategory", b =>
                {
                    b.HasOne("OJS.Data.Models.Contests.ContestCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OJS.Data.Models.Contests.ExamGroup", b =>
                {
                    b.HasOne("OJS.Data.Models.Contests.Contest", "Contest")
                        .WithMany("ExamGroups")
                        .HasForeignKey("ContestId");

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("OJS.Data.Models.FeedbackReport", b =>
                {
                    b.HasOne("OJS.Data.Models.Users.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OJS.Data.Models.IpInContest", b =>
                {
                    b.HasOne("OJS.Data.Models.Contests.Contest", "Contest")
                        .WithMany("IpsInContests")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OJS.Data.Models.Ip", "Ip")
                        .WithMany("IpsInContests")
                        .HasForeignKey("IpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");

                    b.Navigation("Ip");
                });

            modelBuilder.Entity("OJS.Data.Models.LecturerInContest", b =>
                {
                    b.HasOne("OJS.Data.Models.Contests.Contest", "Contest")
                        .WithMany("LecturersInContests")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OJS.Data.Models.Users.UserProfile", "Lecturer")
                        .WithMany("LecturersInContests")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("OJS.Data.Models.LecturerInContestCategory", b =>
                {
                    b.HasOne("OJS.Data.Models.Contests.ContestCategory", "ContestCategory")
                        .WithMany("LecturersInContestCategories")
                        .HasForeignKey("ContestCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OJS.Data.Models.Users.UserProfile", "Lecturer")
                        .WithMany("LecturersInContestCategories")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContestCategory");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("OJS.Data.Models.Participants.Participant", b =>
                {
                    b.HasOne("OJS.Data.Models.Contests.Contest", "Contest")
                        .WithMany("Participants")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OJS.Data.Models.Users.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OJS.Data.Models.Participants.ParticipantScore", b =>
                {
                    b.HasOne("OJS.Data.Models.Participants.Participant", "Participant")
                        .WithMany("Scores")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OJS.Data.Models.Problems.Problem", "Problem")
                        .WithMany("ParticipantScores")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OJS.Data.Models.Submissions.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId");

                    b.Navigation("Participant");

                    b.Navigation("Problem");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("OJS.Data.Models.ProblemForParticipant", b =>
                {
                    b.HasOne("OJS.Data.Models.Participants.Participant", "Participant")
                        .WithMany("ProblemsForParticipants")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OJS.Data.Models.Problems.Problem", "Problem")
                        .WithMany("ProblemsForParticipants")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("OJS.Data.Models.Problems.Problem", b =>
                {
                    b.HasOne("OJS.Data.Models.Checkers.Checker", "Checker")
                        .WithMany()
                        .HasForeignKey("CheckerId");

                    b.HasOne("OJS.Data.Models.Problems.ProblemGroup", "ProblemGroup")
                        .WithMany("Problems")
                        .HasForeignKey("ProblemGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checker");

                    b.Navigation("ProblemGroup");
                });

            modelBuilder.Entity("OJS.Data.Models.Problems.ProblemGroup", b =>
                {
                    b.HasOne("OJS.Data.Models.Contests.Contest", "Contest")
                        .WithMany("ProblemGroups")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("OJS.Data.Models.Problems.ProblemResource", b =>
                {
                    b.HasOne("OJS.Data.Models.Problems.Problem", "Problem")
                        .WithMany("Resources")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("OJS.Data.Models.Submissions.Submission", b =>
                {
                    b.HasOne("OJS.Data.Models.Participants.Participant", "Participant")
                        .WithMany("Submissions")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OJS.Data.Models.Problems.Problem", "Problem")
                        .WithMany("Submissions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OJS.Data.Models.Submissions.SubmissionType", "SubmissionType")
                        .WithMany()
                        .HasForeignKey("SubmissionTypeId");

                    b.Navigation("Participant");

                    b.Navigation("Problem");

                    b.Navigation("SubmissionType");
                });

            modelBuilder.Entity("OJS.Data.Models.SubmissionTypeInProblem", b =>
                {
                    b.HasOne("OJS.Data.Models.Problems.Problem", "Problem")
                        .WithMany("SubmissionTypesInProblems")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OJS.Data.Models.Submissions.SubmissionType", "SubmissionType")
                        .WithMany("SubmissionTypesInProblems")
                        .HasForeignKey("SubmissionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("SubmissionType");
                });

            modelBuilder.Entity("OJS.Data.Models.Tests.Test", b =>
                {
                    b.HasOne("OJS.Data.Models.Problems.Problem", "Problem")
                        .WithMany("Tests")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("OJS.Data.Models.Tests.TestRun", b =>
                {
                    b.HasOne("OJS.Data.Models.Submissions.Submission", "Submission")
                        .WithMany("TestRuns")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OJS.Data.Models.Tests.Test", "Test")
                        .WithMany("TestRuns")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Submission");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("OJS.Data.Models.UserInExamGroup", b =>
                {
                    b.HasOne("OJS.Data.Models.Contests.ExamGroup", "ExamGroup")
                        .WithMany("UsersInExamGroups")
                        .HasForeignKey("ExamGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OJS.Data.Models.Users.UserProfile", "User")
                        .WithMany("UsersInExamGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OJS.Data.Models.Users.UserInRole", b =>
                {
                    b.HasOne("OJS.Data.Models.Users.Role", "Role")
                        .WithMany("UsersInRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OJS.Data.Models.Users.UserProfile", "User")
                        .WithMany("UsersInRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OJS.Data.Models.Users.UserProfile", b =>
                {
                    b.OwnsOne("OJS.Data.Models.Users.UserSettings", "UserSettings", b1 =>
                        {
                            b1.Property<string>("UserProfileId")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("City");

                            b1.Property<string>("Company")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Company");

                            b1.Property<DateTime?>("DateOfBirth")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DateOfBirth");

                            b1.Property<string>("EducationalInstitution")
                                .HasColumnType("text")
                                .HasColumnName("EducationalInstitution");

                            b1.Property<string>("FacultyNumber")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("FacultyNumber");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("JobTitle")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("JobTitle");

                            b1.Property<string>("LastName")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("LastName");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("AspNetUsers");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("UserSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("OJS.Data.Models.Contests.Contest", b =>
                {
                    b.Navigation("ExamGroups");

                    b.Navigation("IpsInContests");

                    b.Navigation("LecturersInContests");

                    b.Navigation("Participants");

                    b.Navigation("ProblemGroups");
                });

            modelBuilder.Entity("OJS.Data.Models.Contests.ContestCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Contests");

                    b.Navigation("LecturersInContestCategories");
                });

            modelBuilder.Entity("OJS.Data.Models.Contests.ExamGroup", b =>
                {
                    b.Navigation("UsersInExamGroups");
                });

            modelBuilder.Entity("OJS.Data.Models.Ip", b =>
                {
                    b.Navigation("IpsInContests");
                });

            modelBuilder.Entity("OJS.Data.Models.Participants.Participant", b =>
                {
                    b.Navigation("ProblemsForParticipants");

                    b.Navigation("Scores");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("OJS.Data.Models.Problems.Problem", b =>
                {
                    b.Navigation("ParticipantScores");

                    b.Navigation("ProblemsForParticipants");

                    b.Navigation("Resources");

                    b.Navigation("SubmissionTypesInProblems");

                    b.Navigation("Submissions");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("OJS.Data.Models.Problems.ProblemGroup", b =>
                {
                    b.Navigation("Problems");
                });

            modelBuilder.Entity("OJS.Data.Models.Submissions.Submission", b =>
                {
                    b.Navigation("TestRuns");
                });

            modelBuilder.Entity("OJS.Data.Models.Submissions.SubmissionType", b =>
                {
                    b.Navigation("SubmissionTypesInProblems");
                });

            modelBuilder.Entity("OJS.Data.Models.Tests.Test", b =>
                {
                    b.Navigation("TestRuns");
                });

            modelBuilder.Entity("OJS.Data.Models.Users.Role", b =>
                {
                    b.Navigation("UsersInRoles");
                });

            modelBuilder.Entity("OJS.Data.Models.Users.UserProfile", b =>
                {
                    b.Navigation("LecturersInContestCategories");

                    b.Navigation("LecturersInContests");

                    b.Navigation("UsersInExamGroups");

                    b.Navigation("UsersInRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
