//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Submissions.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdvancedSubmissions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdvancedSubmissions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Submissions.Views.AdvancedSubmissions", typeof(AdvancedSubmissions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Breadcrumb_home {
            get {
                return ResourceManager.GetString("Breadcrumb_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submissions.
        /// </summary>
        public static string Breadcrumb_submissions {
            get {
                return ResourceManager.GetString("Breadcrumb_submissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest submissions.
        /// </summary>
        public static string Page_title {
            get {
                return ResourceManager.GetString("Page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest {0} submissions out of {1} total.
        /// </summary>
        public static string Page_title_for_regular_user {
            get {
                return ResourceManager.GetString("Page_title_for_regular_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart services.
        /// </summary>
        public static string Restart_service_button_label {
            get {
                return ResourceManager.GetString("Restart_service_button_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all submissions.
        /// </summary>
        public static string Show_all_submissions_label {
            get {
                return ResourceManager.GetString("Show_all_submissions_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show queued submissions.
        /// </summary>
        public static string Show_queued_submissions_label {
            get {
                return ResourceManager.GetString("Show_queued_submissions_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submissions in queue.
        /// </summary>
        public static string Submissions_in_queue_label {
            get {
                return ResourceManager.GetString("Submissions_in_queue_label", resourceCulture);
            }
        }
    }
}
