version: '3.3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    build:
      context: .
      dockerfile: ./db/Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: 1123QwER
      ACCEPT_EULA: "Y"
    restart: always
    # volumes:
    #   - ./sql_server/data:/var/opt/mssql/data
    #   - ./sql_server/log:/var/opt/mssql/log
    #   - ./sql_server/secrets:/var/opt/mssql/secrets
  app:
    image: ui_for_tests
    build:
      context: ../
      dockerfile: Servers/UI/OJS.Servers.Ui/Dockerfile
    ports:
      - "7150:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DbContext: "Server=localhost;Database=OpenJudgeSystem;User Id=sa;Password=1123QwER"
      SULS_PLATFORM_BASE_URL: "https://localhost:44304"
      DISTRIBUTOR_BASE_URL: "https://localhost:44305"
      SULS_PLATFORM_API_KEY: "1234"
      LOGGER_FILES_FOLDER_PATH: "../../../Logs"
      SHARED_AUTH_COOKIE_DOMAIN: "localhost"
      UI_URL: "http://localhost:5002"
      ADMINISTRATION_URL: "http://localhost:5001"
      UI_HOME_YOUTUBE_VIDEO_ID: "IwLET8SDBE4"
  tests:
    image: tests
    # command: tail -F anything
    container_name: tests_instance
    network_mode: host
    build:
      context: .
      dockerfile: ./test/Dockerfile
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./restore:/queries/restore
