//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Navigation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Navigation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.Navigation", typeof(Navigation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access logs.
        /// </summary>
        public static string Access_Logs_Link {
            get {
                return ResourceManager.GetString("Access_Logs_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category hierarchy.
        /// </summary>
        public static string Contest_Categories_Hierarchy_Link {
            get {
                return ResourceManager.GetString("Contest_Categories_Hierarchy_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest categories.
        /// </summary>
        public static string Contest_Categories_Link {
            get {
                return ResourceManager.GetString("Contest_Categories_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contests.
        /// </summary>
        public static string Contests_Link {
            get {
                return ResourceManager.GetString("Contests_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam groups.
        /// </summary>
        public static string Exam_Groups_Link {
            get {
                return ResourceManager.GetString("Exam_Groups_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback_Link {
            get {
                return ResourceManager.GetString("Feedback_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles_Link {
            get {
                return ResourceManager.GetString("Roles_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Link {
            get {
                return ResourceManager.GetString("Settings_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submissions.
        /// </summary>
        public static string Submissions_Link {
            get {
                return ResourceManager.GetString("Submissions_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks_Link {
            get {
                return ResourceManager.GetString("Tasks_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test files.
        /// </summary>
        public static string Tests_Link {
            get {
                return ResourceManager.GetString("Tests_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users_Link {
            get {
                return ResourceManager.GetString("Users_Link", resourceCulture);
            }
        }
    }
}
