name: Deploy PROD Admin

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: 'The docker tag that will be pushed when the selected Branch is build'
        required: true
        default: "latest"
        type: string
  workflow_call:
    inputs:
      docker_image_tag:
        required: true
        default: "latest"
        type: string
jobs:
  check-user-access:
    uses: ./.github/workflows/check-prod-deploy-user-access.yml
    secrets: inherit
  build-and-push:
    needs: [check-user-access]
    if: ${{ needs.check-user-access.outputs.isTeamMember == 'true' }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_image_name: judge_web_administration
      dockerfile_name: Dockerfile.administration
      docker_tag: ${{ inputs.docker_image_tag }}
    secrets: inherit
  deploy:
    needs: [build-and-push]
    uses: ./.github/workflows/deploy.yml
    secrets:
      webhook_url: ${{ secrets.ADMIN_PROD_WEBHOOK_URL }}
      webhook_secret: ${{ secrets.WEBHOOK_PROD_SECRET }}