name: Administration Build

on:
  push:
    branches:
      - "v2"
  pull_request:
    types:
      - "ready_for_review"
    branches:
      - "*"
jobs:
    call-workflow-passing-data:
        uses: ./.github/workflows/build.yml
        with:
            docker_image_name: judge_web_administration
            dockerfile_name: Dockerfile.administration
        secrets: inherit