name: Administration dev deploy

on:
  workflow_dispatch:
jobs:
    build:
        uses: ./.github/workflows/build.yml
        with:
            docker_image_name: judge_web_administration
            dockerfile_name: Dockerfile.administration
            docker_tag: dev-latest
            branch_name: v2-development
        secrets: inherit
    deploy:
        needs: [build]
        uses: ./.github/workflows/deploy.yml
        secrets:
            webhook_url: ${{ secrets.ADMIN_WEBHOOK_URL }}
            webhook_secret: ${{ secrets.WEBHOOK_SECRET }}