name: Administration Build

on:
  push:
    branches:
      - "v2"
  pull_request:
    types:
      - "ready_for_review"
    branches:
      - "*"
jobs:
  build-and-push-admin:
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_image_name: judge_web_administration
      dockerfile_name: Dockerfile.administration
    secrets: inherit
