name: Z. Build and Push (called)

on:
    workflow_call:
      inputs:
        docker_image_name:
          required: true
          type: string
        dockerfile_name:
          required: true
          type: string
        docker_tag:
          required: false
          type: string
        branch_name:
            required: false
            type: string
        push_to_registry:
          required: false
          default: true
          type: boolean
        additional_run_commands:
          required: false
          type: string
        build_args:
          required: false
          type: string

env:
    IMG: ${{ inputs.docker_image_name }}
    DOCKERFILE_PATH: Docker/${{ inputs.dockerfile_name }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Environment Variables
      run: |
        OWNER="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
        echo "BUILD_VER=1.0.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
        echo "IMG=${IMG}" >> $GITHUB_ENV
        echo "IMAGE=ghcr.io/${OWNER}/${IMG}" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
        ${{ inputs.additional_run_commands }}
    - name: Get branch name (merge)
      if: github.event_name == 'push'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
    - name: Get branch name (pull request)
      if: github.event_name == 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
    - name: Get docker tag
      shell: bash
      run: echo "DOCKER_TAG=${{ inputs.docker_tag }}" >> $GITHUB_ENV

    - name: Checkout
      if: inputs.branch_name == ''
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.SOFTUNIBUILD_PAT }}
    - name: Checkout predefined branch
      if: inputs.branch_name != ''
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch_name }}
        submodules: recursive
        token: ${{ secrets.SOFTUNIBUILD_PAT }}

    - name: Prepare Docker Tags
      id: prepare_docker_tags
      shell: bash
      run: |
        TAGS=""
        if [[ -n "${{ inputs.docker_image_tag }}" ]]; then
          CURRENT_DATE=$(date +'%d-%m-%Y_%H%M')
          TAGS="${{ env.IMAGE }}:${CURRENT_DATE},${{ env.IMAGE }}:${{ env.GIT_SHA }},${{ env.IMAGE }}:${{ env.BUILD_VER }}"
        else
          TAGS="${{ env.IMAGE }}:${{ env.GIT_SHA }},${{ env.IMAGE }}:${{ env.BUILD_VER }}"
        fi
        if [[ -n "${{ env.BRANCH_NAME }}" ]]; then
          TAGS="$TAGS,${{ env.IMAGE }}:${{ env.BRANCH_NAME }}"
        fi
        if [[ -n "${{ env.DOCKER_TAG }}" ]]; then
          TAGS="$TAGS,${{ env.IMAGE }}:${{ env.DOCKER_TAG }}"
        fi
        echo "DOCKER_TAGS=$TAGS" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        install: true
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.SOFTUNIBUILD_USER }}
        password: ${{ secrets.SOFTUNIBUILD_PAT }} # - must be in GitHub Secrets!
    - uses: docker/build-push-action@v4
      with:
        context: .
        registry: ghcr.io
        file: ${{ env.DOCKERFILE_PATH }}
        builder: ${{ steps.buildx.outputs.name }}
        build-args: |
          ${{ inputs.build_args }}
        labels: |
          org.opencontainers.image.authors=${{ github.repository_owner }}
          org.opencontainers.image.created=${{ env.BUILD_DATE }}
          org.opencontainers.image.description=Created from commit ${{ env.GIT_SHA }} and ref ${{ env.GIT_REF }}
          org.opencontainers.image.ref.name=${{ env.GIT_REF }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.version=${{ env.BUILD_VER }}
        tags: ${{ env.DOCKER_TAGS }}
        push: ${{ inputs.push_to_registry }}
        platforms: linux/amd64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        secrets: |
          GIT_AUTH_TOKEN=${{ github.token }}
