on:
  workflow_call:
    secrets:
      webhook_url:
        required: true
      webhook_secret:
        required: true

jobs:
  check-user-access:
    runs-on: ubuntu-latest
    outputs:
      isTeamMember: ${{ steps.checkUserMember.outputs.isTeamMember }}
    steps:
    - name: Check if user is in team 'Alpha Judge Prod deploy'
      id: checkUserMember
      uses: tspascoal/get-user-teams-membership@v1.0.0
      with:
        username: ${{ github.triggering_actor }}
        team: 'Alpha Judge Prod deploy'
        GITHUB_TOKEN: ${{ secrets.SOFTUNIBUILD_PAT }}