on:
  workflow_call:
    secrets:
      webhook_url:
        required: true
      webhook_secret:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v3
      env:
        webhook_url: ${{ secrets.webhook_url }}
        webhook_secret: ${{ secrets.webhook_secret }}