name: 01. Deploy All (Development)

on:
  workflow_dispatch:
jobs:
  build-and-deploy-admin:
    uses: ./.github/workflows/admin-dev-deploy.yml
    secrets: inherit
  build-and-deploy-ui:
    uses: ./.github/workflows/ui-dev-deploy.yml
    secrets: inherit
