name: Z. Deploy worker (called)

on:
  workflow_call:
    inputs:
      environment:
        required: false
        default: "development"
        type: string
      workers_count:
        required: false
        default: 8
        type: number
    secrets:
      host:
        required: true
      username:
        required: true
      key:
        required: true
      port:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke deployment over SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        key: ${{ secrets.key }}
        port: ${{ secrets.port }}
        script: |
          docker-compose -f /home/admins/repos/judge-workers-deployment/judge-web/${{ inputs.environment }}/docker-compose.workers.${{ inputs.workers_count }}.yml pull
          docker-compose -f /home/admins/repos/judge-workers-deployment/judge-web/${{ inputs.environment }}/docker-compose.workers.${{ inputs.workers_count }}.yml up -d