name: Z. Deploy (called)

on:
  workflow_call:
    inputs:
      payload:
        required: false
        type: string
    secrets:
      webhook_url:
        required: true
      webhook_secret:
        required: true
      docker_username:
        required: true
      docker_password:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v3
      with:
        webhook_url: ${{ secrets.webhook_url }}
        webhook_secret: ${{ secrets.webhook_secret }}
        data: |
          {
            "username": "${{ secrets.docker_username }}",
            "password": "${{ secrets.docker_password }}",
            "payload": "${{ inputs.payload || '{}' }}"
          }
