name: Deploy PROD All

on:
  workflow_dispatch:
jobs:
    build-and-deploy-admin:
        uses: ./.github/workflows/admin-prod-deploy.yml
        secrets: inherit
    build-and-deploy-ui:
        uses: ./.github/workflows/ui-prod-deploy.yml
        secrets: inherit
