name: 01. Deploy All (Development)

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'The branch that will be deployed'
        required: true
        default: "v2-development"
        type: string
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
jobs:
  build-and-deploy-admin:
    uses: ./.github/workflows/admin-dev-deploy.yml
    with:
      branch_name: ${{ inputs.branch_name }}
    secrets: inherit
  build-and-deploy-ui:
    uses: ./.github/workflows/ui-dev-deploy.yml
    with:
      branch_name: ${{ inputs.branch_name }}
    secrets: inherit
  build-and-deploy-fe:
    uses: ./.github/workflows/fe-dev-deploy.yml
    with:
      branch_name: ${{ inputs.branch_name }}
    secrets: inherit
  build-and-deploy-worker:
    uses: ./.github/workflows/worker-dev-deploy.yml
    with:
      branch_name: ${{ inputs.branch_name }}
    secrets: inherit
    
