name: Build FE

on:
  push:
    branches:
      - "v2"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - "*"
jobs:
  build-and-push-fe:
    name: FE build and push
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_image_name: judge_web_fe
      dockerfile_name: Dockerfile.fe
      build_command: build
      additional_run_commands: |
        echo "NODE_OPTIONS=--max_old_space_size=8192" >> $GITHUB_ENV
        export NODE_OPTIONS=--max-old-space-size=8192
    secrets: inherit