name: Run Integration Tests

on:
  schedule:
    - cron: "0 0 * * *" # Runs every night at 12:00 AM UTC
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.SOFTUNIBUILD_USER }}
          password: ${{ secrets.SOFTUNIBUILD_PAT }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run IntegrationTests.Worker
        run: dotnet test --logger "console;verbosity=detailed"