name: Run Integration Tests

on:
  schedule:
    - cron: "0 0 * * *" # Runs every night at 12:00 AM UTC
  workflow_dispatch:

jobs:
  integration-tests:
    name: Integration Worker Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run IntegrationTests.Worker
        run: dotnet test --logger "console;verbosity=detailed"