name: PR merged to development

on:
  pull_request:
    types: [closed]
    branches:
      - v2-development

  build-and-deploy:
    needs: check-if-merged
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/deploy-dev-all.yml
    with:
      branch_name: v2-development
    secrets: inherit
