name: PR review submitted

on:
  pull_request_review:
    types: [submitted]
jobs:
  return-issues-for-changes-on-pr-requested-changes:
    if: github.event.review.state == 'changes_requested'
    uses: ./.github/workflows/update-linked-issues-status.yml
    with:
      status_name: 2. Returned for changes
    secrets: inherit
