name: PR merged to development

on:
  pull_request:
    types: [closed]
    branches:
      - v2-development

jobs:
  build-and-deploy-to-dev-on-pr-merge:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/deploy-dev-all.yml
    with:
      branch_name: v2-development
    secrets: inherit
