name: Build

on:
  push:
    branches:
      - "v2"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - "*"
jobs:
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      push_to_registry: ${{ steps.set-vars.outputs.push_to_registry }}
    steps:
      - id: set-vars
        name: Determine if branch is v2 and set push_to_registry
        run: |
          echo "push_to_registry=${{ github.event_name == 'push' && github.ref == 'refs/heads/v2' }}" >> "$GITHUB_OUTPUT"

  build-fe:
    name: Front-End build
    needs: check-branch
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_image_name: judge_web_fe
      dockerfile_name: Dockerfile.fe
      push_to_registry: ${{ needs.check-branch.outputs.push_to_registry  == 'true' }}
      build_args: YARN_BUILD_COMMAND=build
    secrets: inherit
  build-ui:
    name: UI api build
    needs: check-branch
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_image_name: judge_web_ui
      dockerfile_name: Dockerfile.ui
      push_to_registry: ${{ needs.check-branch.outputs.push_to_registry  == 'true' }}
    secrets: inherit
  build-admin:
    name: Administration api build
    needs: check-branch
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_image_name: judge_web_administration
      dockerfile_name: Dockerfile.administration
      push_to_registry: ${{ needs.check-branch.outputs.push_to_registry  == 'true' }}
    secrets: inherit
  build-worker:
    name: Worker build
    needs: check-branch
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_image_name: judge_worker
      dockerfile_name: Dockerfile.worker
      push_to_registry: ${{ needs.check-branch.outputs.push_to_registry  == 'true' }}
    secrets: inherit