name: PR opened

on:
  pull_request:
    types:
      - opened
jobs:
  move-issues-to-in-review-on-pr-opened:
    uses: ./.github/workflows/update-linked-issues-status.yml
    with:
      status_name: 4. In review
    secrets: inherit
