name: Build

on:
  push:
    branches:
      - "v2"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - "*"
jobs:
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      push_to_registry: ${{ steps.set-vars.outputs.push_to_registry }}
    steps:
      - name: Determine if branch is v2 and set push_to_registry
        id: set-vars
        run: |
          echo "push_to_registry=${{ github.event_name == 'push' && github.ref == 'refs/heads/v2' }}" >> "$GITHUB_OUTPUT"

  build-fe:
    name: Front-End build
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_image_name: judge_web_fe
      dockerfile_name: Dockerfile.fe
      push_to_registry: "${{ needs.check-branch.outputs.push_to_registry }}"
      build_args: YARN_BUILD_COMMAND=build
      additional_run_commands: |
        echo "NODE_OPTIONS=--max_old_space_size=8192" >> $GITHUB_ENV
        export NODE_OPTIONS=--max-old-space-size=8192
    secrets: inherit
  build-ui:
    name: UI api build
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_image_name: judge_web_ui
      dockerfile_name: Dockerfile.ui
      push_to_registry: "${{ needs.check-branch.outputs.push_to_registry }}"
    secrets: inherit
  build-admin:
    name: Administration api build
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_image_name: judge_web_administration
      dockerfile_name: Dockerfile.administration
      push_to_registry: "${{ needs.check-branch.outputs.push_to_registry }}"
    secrets: inherit
  build-worker:
    name: Worker build
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_image_name: judge_worker
      dockerfile_name: Dockerfile.worker
      push_to_registry: "${{ needs.check-branch.outputs.push_to_registry }}"
    secrets: inherit