name: UI dev deploy



on:
  push:
    branches:
      - "setup-v2-development-gha-workflows"
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Environment Variables
      run: |
        IMG=judge_web_ui
        OWNER="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
        echo "BUILD_VER=1.0.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
        echo "IMG=${IMG}" >> $GITHUB_ENV
        echo "IMAGE=ghcr.io/${OWNER}/${IMG}" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
        echo "DOCKERFILE_PATH=Docker/Dockerfile.ui" >> $GITHUB_ENV
        echo "DOCKER_COMPOSE_FILE_PATH=/home/admins/repos/judge-workers-deployment/judge-web/docker-compose.development.yml" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.SOFTUNIBUILD_PAT }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
      with:
        version: latest
        install: true
    - name: Cache Docker layers
      uses: actions/cache@v3.0.9
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: softuni-build
        password: ${{ secrets.SOFTUNIBUILD_PAT }} # - must be in GitHub Secrets!
    - uses: docker/build-push-action@v2
      with:
        context: .
        registry: ghcr.io
        file: ${{ env.DOCKERFILE_PATH }}
        builder: ${{ steps.buildx.outputs.name }}
        labels: |
          org.opencontainers.image.authors=${{ github.repository_owner }}
          org.opencontainers.image.created=${{ env.BUILD_DATE }}
          org.opencontainers.image.description=Created from commit ${{ env.GIT_SHA }} and ref ${{ env.GIT_REF }}
          org.opencontainers.image.ref.name=${{ env.GIT_REF }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.version=${{ env.BUILD_VER }}
        tags: |
          ${{ env.IMAGE }}:${{ env.GIT_SHA }}
          ${{ env.IMAGE }}:${{ env.BUILD_VER }}
          ${{ env.IMAGE }}:dev-latest
        push: true
        platforms: linux/amd64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        secrets: |
          GIT_AUTH_TOKEN=${{ github.token }}
    - name: Deploy to dev server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_DEV_UI_HOST }}
        username: ${{ secrets.SSH_DEV_UI_USERNAME }}
        password: ${{ secrets.SSH_DEV_UI_PASSWORD }}
        script: |
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE_PATH }} pull ui
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE_PATH }} up -d --force-recreate ui nginx