name: UI dev deploy

on:
  workflow_dispatch:
  workflow_call:
jobs:
    build-push-and-deploy-ui:
        uses: ./.github/workflows/build.yml
        with:
            deploy: true
            docker_image_name: judge_web_ui
            dockerfile_name: Dockerfile.ui
            docker_tag: dev-latest
            branch_name: v2-development
            additional_run_commands: |
                echo "NODE_OPTIONS=--max_old_space_size=8192" >> $GITHUB_ENV
                export NODE_OPTIONS=--max-old-space-size=8192
        secrets:
            webhook_url: ${{ secrets.ADMIN_WEBHOOK_URL }}
            webhook_secret: ${{ secrets.WEBHOOK_SECRET }}