name: Deploy PROD UI

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: 'The docker tag that will be pushed when the selected Branch is build'
        required: true
        default: "latest"
        type: string
  workflow_call:
    inputs:
      docker_image_tag:
        required: true
        type: string
      branch_name:
        description: 'The branch that will be deployed'
        required: false
        type: string
jobs:
  check-user-access:
    runs-on: ubuntu-latest
    outputs:
      isTeamMember: ${{ steps.checkUserMember.outputs.isTeamMember }}
    steps:
    - name: Check if user is in team 'Alpha Judge Prod deploy'
      id: checkUserMember
      uses: tspascoal/get-user-teams-membership@v2
      with:
        username: ${{ github.triggering_actor }}
        team: 'Alpha Judge Prod deploy'
        GITHUB_TOKEN: ${{ secrets.SOFTUNIBUILD_PAT }}
  build-and-push:
    needs: [check-user-access]
    if: ${{ needs.check-user-access.outputs.isTeamMember == 'true' }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_image_name: judge_web_ui
      dockerfile_name: Dockerfile.ui
      docker_tag: ${{ inputs.docker_image_tag }}
      branch_name: ${{ inputs.branch_name || 'v2' }}
      additional_run_commands: |
        echo "NODE_OPTIONS=--max_old_space_size=8192" >> $GITHUB_ENV
        export NODE_OPTIONS=--max-old-space-size=8192
    secrets: inherit
  deploy:
    needs: [build-and-push]
    uses: ./.github/workflows/deploy.yml
    secrets:
      webhook_url: ${{ secrets.UI_PROD_WEBHOOK_URL }}
      webhook_secret: ${{ secrets.WEBHOOK_PROD_SECRET }}
      docker_username: ${{ secrets.SOFTUNIBUILD_USER }}
      docker_password: ${{ secrets.SOFTUNIBUILD_PAT }}