name: Deploy PROD - UI

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        required: true
        default: "latest"
        type: string
jobs:
  check-user-access:
    uses: ./.github/workflows/check-prod-deploy-user-access.yml
    secrets: inherit
  build-and-push:
    needs: [check-user-access]
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_image_name: judge_web_ui
      dockerfile_name: Dockerfile.ui
      docker_tag: ${{ inputs.docker_image_tag }}
      additional_run_commands: |
        echo "NODE_OPTIONS=--max_old_space_size=8192" >> $GITHUB_ENV
        export NODE_OPTIONS=--max-old-space-size=8192
    secrets: inherit
  deploy:
    needs: [build-and-push]
    uses: ./.github/workflows/deploy.yml
    secrets:
      webhook_url: ${{ secrets.UI_PROD_WEBHOOK_URL }}
      webhook_secret: ${{ secrets.WEBHOOK_PROD_SECRET }}