name: 04. Deploy Worker (Development)

on:
  workflow_dispatch:
  workflow_call:
jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_image_name: judge_worker_v2
      dockerfile_name: Dockerfile.worker
      docker_tag: dev-latest
      branch_name: v2-development
    secrets: inherit
  deploy:
    needs: [build-and-push]
    uses: ./.github/workflows/deploy.yml
    secrets:
      webhook_url: ${{ secrets.WORKER_WEBHOOK_URL }}
      webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
