name: 04. Deploy Worker (Development)

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch_name:
        description: 'The branch that will be deployed'
        required: false
        type: string
jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_image_name: judge_worker
      dockerfile_name: Dockerfile.worker
      docker_tag: dev-latest
      branch_name: ${{ inputs.branch_name || 'v2-development' }}
    secrets: inherit
  deploy:
    needs: [build-and-push]
    uses: ./.github/workflows/deploy.yml
    secrets:
      payload: |
        {
          "urls": [
            "http://217.174.159.185:9000/hooks/redeploy-worker"
          ]
        }
      webhook_url: ${{ secrets.WORKER_WEBHOOK_URL }}
      webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
      docker_username: ${{ secrets.SOFTUNIBUILD_USER }}
      docker_password: ${{ secrets.SOFTUNIBUILD_PAT }}
