name: Build Worker

on:
  push:
    branches:
      - "v2"
  pull_request:
    types:
      - "ready_for_review"
    branches:
      - "*"
jobs:
  build-and-push-worker:
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_image_name: judge_worker
      dockerfile_name: Dockerfile.worker
    secrets: inherit
